// Türkiye'deki en yaygın ~500 üniversite bölümü
export const DEPARTMENTS: string[] = [
  // Tıp ve Sağlık Bilimleri
  "Tıp",
  "Diş Hekimliği",
  "Eczacılık",
  "Hemşirelik",
  "Ebelik",
  "Fizyoterapi ve Rehabilitasyon",
  "Beslenme ve Diyetetik",
  "Ergoterapi",
  "Odyoloji",
  "Çocuk Gelişimi",
  "Sağlık Yönetimi",
  "Acil Yardım ve Afet Yönetimi",
  "Paramedik",
  "Sosyal Hizmet",
  "Gerontoloji",
  "Perfüzyon",
  "Ortez ve Protez",
  "Dil ve Konuşma Terapisi",
  "Veteriner Hekimlik",
  "Biyomedikal Mühendisliği",
  "Genetik ve Biyomühendislik",
  "Sağlık Memurluğu",
  "Radyoterapi",
  "Tıbbi Laboratuvar Teknikleri",
  "Tıbbi Görüntüleme Teknikleri",
  "Anestezi",
  "Ameliyathane Hizmetleri",
  "İlk ve Acil Yardım",
  "Tıbbi Dokümantasyon ve Sekreterlik",
  "Ağız ve Diş Sağlığı",
  "Optisyenlik",
  "Podoloji",

  // Mühendislik
  "Bilgisayar Mühendisliği",
  "Elektrik-Elektronik Mühendisliği",
  "Makine Mühendisliği",
  "İnşaat Mühendisliği",
  "Endüstri Mühendisliği",
  "Kimya Mühendisliği",
  "Çevre Mühendisliği",
  "Gıda Mühendisliği",
  "Metalurji ve Malzeme Mühendisliği",
  "Mekatronik Mühendisliği",
  "Yazılım Mühendisliği",
  "Havacılık ve Uzay Mühendisliği",
  "Biyomühendislik",
  "Jeoloji Mühendisliği",
  "Jeofizik Mühendisliği",
  "Maden Mühendisliği",
  "Petrol ve Doğalgaz Mühendisliği",
  "Tekstil Mühendisliği",
  "Orman Mühendisliği",
  "Harita Mühendisliği",
  "Otomotiv Mühendisliği",
  "Enerji Sistemleri Mühendisliği",
  "Kontrol ve Otomasyon Mühendisliği",
  "Deniz Ulaştırma İşletme Mühendisliği",
  "Gemi İnşaatı ve Gemi Makineleri Mühendisliği",
  "Nükleer Enerji Mühendisliği",
  "Polimer Mühendisliği",
  "Biyosistem Mühendisliği",
  "Elektronik ve Haberleşme Mühendisliği",
  "Bilişim Sistemleri Mühendisliği",
  "Malzeme Bilimi ve Mühendisliği",
  "Fizik Mühendisliği",
  "Matematik Mühendisliği",
  "Uçak Mühendisliği",
  "Uzay Mühendisliği",
  "Savunma Teknolojileri Mühendisliği",
  "Yapay Zeka Mühendisliği",
  "Nanoteknoloji Mühendisliği",
  "Biyokimya Mühendisliği",
  "Tarımsal Yapılar ve Sulama Mühendisliği",
  "Ziraat Mühendisliği",
  "Peyzaj Mimarlığı",

  // Fen Bilimleri
  "Matematik",
  "Fizik",
  "Kimya",
  "Biyoloji",
  "Moleküler Biyoloji ve Genetik",
  "İstatistik",
  "Astronomi ve Uzay Bilimleri",
  "Aktüerya Bilimleri",
  "Biyoteknoloji",
  "Biyoinformatik",
  "Nanobilim ve Nanoteknoloji",

  // Mimarlık ve Tasarım
  "Mimarlık",
  "İç Mimarlık",
  "İç Mimarlık ve Çevre Tasarımı",
  "Şehir ve Bölge Planlama",
  "Endüstriyel Tasarım",
  "Endüstri Ürünleri Tasarımı",
  "Grafik Tasarım",
  "Moda Tasarımı",
  "Moda ve Tekstil Tasarımı",
  "Tekstil ve Moda Tasarımı",
  "Görsel İletişim Tasarımı",
  "İletişim Tasarımı",
  "Çizgi Film ve Animasyon",
  "Oyun Tasarımı",
  "Dijital Oyun Tasarımı",

  // Hukuk
  "Hukuk",
  "Adalet",

  // İktisadi ve İdari Bilimler
  "İktisat",
  "İşletme",
  "Maliye",
  "Kamu Yönetimi",
  "Siyaset Bilimi ve Kamu Yönetimi",
  "Siyaset Bilimi ve Uluslararası İlişkiler",
  "Uluslararası İlişkiler",
  "Uluslararası Ticaret ve Finansman",
  "Uluslararası Ticaret",
  "Uluslararası Ticaret ve İşletmecilik",
  "Uluslararası Ticaret ve Lojistik",
  "Uluslararası Finans",
  "Bankacılık ve Finans",
  "Bankacılık ve Sigortacılık",
  "Sigortacılık ve Sosyal Güvenlik",
  "Muhasebe ve Finansal Yönetim",
  "Yönetim Bilişim Sistemleri",
  "Lojistik Yönetimi",
  "Havacılık Yönetimi",
  "Denizcilik İşletmeleri Yönetimi",
  "Turizm İşletmeciliği",
  "Turizm ve Otel İşletmeciliği",
  "Turizm Rehberliği",
  "Turizm ve Seyahat Hizmetleri",
  "Gastronomi ve Mutfak Sanatları",
  "Çalışma Ekonomisi ve Endüstri İlişkileri",
  "Ekonometri",
  "Ekonomi",
  "Girişimcilik",
  "Pazarlama",
  "Dış Ticaret",
  "E-Ticaret ve Pazarlama",
  "İnsan Kaynakları Yönetimi",
  "Sigortacılık ve Risk Yönetimi",

  // Eğitim Bilimleri
  "Sınıf Öğretmenliği",
  "Okul Öncesi Öğretmenliği",
  "İlköğretim Matematik Öğretmenliği",
  "Matematik Öğretmenliği",
  "Fen Bilgisi Öğretmenliği",
  "Fizik Öğretmenliği",
  "Kimya Öğretmenliği",
  "Biyoloji Öğretmenliği",
  "Türkçe Öğretmenliği",
  "Türk Dili ve Edebiyatı Öğretmenliği",
  "Sosyal Bilgiler Öğretmenliği",
  "Tarih Öğretmenliği",
  "Coğrafya Öğretmenliği",
  "İngilizce Öğretmenliği",
  "Almanca Öğretmenliği",
  "Fransızca Öğretmenliği",
  "Müzik Öğretmenliği",
  "Resim-İş Öğretmenliği",
  "Beden Eğitimi ve Spor Öğretmenliği",
  "Özel Eğitim Öğretmenliği",
  "Rehberlik ve Psikolojik Danışmanlık",
  "Eğitim Bilimleri",
  "Bilgisayar ve Öğretim Teknolojileri Öğretmenliği",
  "Din Kültürü ve Ahlak Bilgisi Öğretmenliği",
  "Arapça Öğretmenliği",
  "Japonca Öğretmenliği",
  "İspanyolca Öğretmenliği",
  "Rusça Öğretmenliği",

  // İletişim
  "Gazetecilik",
  "Halkla İlişkiler ve Tanıtım",
  "Radyo, Televizyon ve Sinema",
  "Reklamcılık",
  "Yeni Medya",
  "Yeni Medya ve İletişim",
  "Dijital Medya",
  "Medya ve İletişim",
  "Medya ve İletişim Sistemleri",
  "Fotoğrafçılık",
  "Sinema ve Televizyon",
  "Halkla İlişkiler ve Reklamcılık",
  "Basım ve Yayın Teknolojileri",

  // Güzel Sanatlar
  "Resim",
  "Heykel",
  "Seramik",
  "Cam",
  "Tekstil Tasarımı",
  "Takı Tasarımı",
  "Fotoğraf",
  "Geleneksel Türk Sanatları",
  "Sahne Sanatları",
  "Tiyatro",
  "Müzik",
  "Müzikoloji",
  "Kompozisyon",
  "Opera",
  "Bale",
  "Dans",
  "Çalgı Yapımı",
  "Türk Müziği",
  "Türk Halk Müziği",
  "Türk Sanat Müziği",
  "Caz",

  // Edebiyat ve Beşeri Bilimler
  "Türk Dili ve Edebiyatı",
  "İngiliz Dili ve Edebiyatı",
  "Amerikan Kültürü ve Edebiyatı",
  "Alman Dili ve Edebiyatı",
  "Fransız Dili ve Edebiyatı",
  "İspanyol Dili ve Edebiyatı",
  "İtalyan Dili ve Edebiyatı",
  "Rus Dili ve Edebiyatı",
  "Arap Dili ve Edebiyatı",
  "Fars Dili ve Edebiyatı",
  "Japon Dili ve Edebiyatı",
  "Çin Dili ve Edebiyatı",
  "Kore Dili ve Edebiyatı",
  "Karşılaştırmalı Edebiyat",
  "Mütercim-Tercümanlık",
  "Mütercim-Tercümanlık (İngilizce)",
  "Mütercim-Tercümanlık (Almanca)",
  "Mütercim-Tercümanlık (Fransızca)",
  "Mütercim-Tercümanlık (Arapça)",
  "Mütercim-Tercümanlık (Rusça)",
  "Çeviribilim",
  "Dilbilim",
  "Felsefe",
  "Tarih",
  "Sanat Tarihi",
  "Arkeoloji",
  "Antropoloji",
  "Sosyoloji",
  "Psikoloji",
  "Coğrafya",
  "Bilgi ve Belge Yönetimi",
  "Kültürel Çalışmalar",
  "Halkbilim",
  "Müzecilik",
  "Eski Yunan Dili ve Edebiyatı",
  "Latin Dili ve Edebiyatı",
  "Hindoloji",
  "Hungaroloji",
  "Bulgar Dili ve Edebiyatı",
  "Gürcü Dili ve Edebiyatı",
  "Kürt Dili ve Edebiyatı",
  "Çağdaş Türk Lehçeleri ve Edebiyatları",

  // İlahiyat ve İslami İlimler
  "İlahiyat",
  "İslami İlimler",
  "Temel İslam Bilimleri",
  "İslam Ekonomisi ve Finans",

  // Spor Bilimleri
  "Antrenörlük Eğitimi",
  "Spor Yöneticiliği",
  "Rekreasyon",
  "Egzersiz ve Spor Bilimleri",
  "Spor Bilimleri",

  // Ziraat ve Orman
  "Bahçe Bitkileri",
  "Bitki Koruma",
  "Hayvansal Üretim",
  "Tarım Ekonomisi",
  "Tarla Bitkileri",
  "Toprak Bilimi ve Bitki Besleme",
  "Su Ürünleri",
  "Balıkçılık Teknolojisi Mühendisliği",
  "Orman Endüstri Mühendisliği",
  "Yaban Hayatı Ekolojisi ve Yönetimi",
  "Peyzaj Mimarlığı",
  "Zootekni",
  "Süt Teknolojisi",
  "Tarım Makineleri ve Teknolojileri Mühendisliği",

  // Bilgi Teknolojileri ve Bilişim
  "Bilgisayar Bilimleri",
  "Bilgisayar Programcılığı",
  "Bilgi Teknolojileri",
  "Bilişim Güvenliği",
  "Siber Güvenlik",
  "Yapay Zeka",
  "Veri Bilimi",
  "Bilgisayar ve Yazılım Mühendisliği",
  "Web Tasarımı ve Kodlama",
  "Bilgi Sistemleri ve Teknolojileri",

  // Denizcilik
  "Deniz Ulaştırma İşletme",
  "Deniz ve Liman İşletmeciliği",
  "Gemi Makineleri İşletme Mühendisliği",
  "Gemi ve Deniz Teknolojisi Mühendisliği",
  "Denizcilik İşletmeleri Yönetimi",

  // Havacılık
  "Pilotaj",
  "Uçak Gövde ve Motor Bakımı",
  "Sivil Hava Ulaştırma İşletmeciliği",
  "Havacılık Elektrik ve Elektroniği",
  "Uçuş Harekat Yöneticiliği",
  "Havacılık ve Uzay Mühendisliği",

  // Uygulamalı Bilimler
  "Bankacılık ve Finans",
  "Muhasebe Bilgi Sistemleri",
  "Aşçılık",
  "Pastacılık ve Fırıncılık",
  "Gıda Teknolojisi",
  "Otopark Hizmetleri",
  "Sivil Havacılık Kabin Hizmetleri",
  "Seyahat İşletmeciliği",
  "Moda Tasarımı",
  "İç Mekan Tasarımı",
  "Mobilya ve Dekorasyon",
  "Elektronik Teknolojisi",
  "Elektrik",
  "Otomotiv Teknolojisi",
  "İklimlendirme ve Soğutma Teknolojisi",
  "İnşaat Teknolojisi",
  "Bilgisayar Teknolojisi",
  "İnternet ve Ağ Teknolojileri",
  "Grafik Tasarım",
  "Radyo ve Televizyon Teknolojisi",
  "Harita ve Kadastro",
  "Laborant ve Veteriner Sağlık",
  "Büro Yönetimi ve Yönetici Asistanlığı",
  "Yerel Yönetimler",

  // Diğer Popüler Bölümler
  "Uluslararası İlişkiler ve Avrupa Birliği",
  "Kamu Yönetimi ve Siyaset Bilimi",
  "Medya ve Kültürel Çalışmalar",
  "Film Tasarımı ve Yönetimi",
  "Görsel Sanatlar",
  "Ulaştırma ve Lojistik",
  "Enerji Yönetimi",
  "Kentsel Tasarım ve Peyzaj Mimarlığı",
  "Gayrimenkul Geliştirme ve Yönetimi",
  "Sermaye Piyasası",
  "Hava Trafik Kontrolörlüğü",
  "Savaş Uçağı Pilotluğu",
  "Uzay Bilimleri ve Teknolojileri",
  "Raylı Sistemler Mühendisliği",
  "Otomotiv Mühendisliği",
  "Uçak Mühendisliği",
  "Mantar Yetiştiriciliği",
  "Arıcılık",
  "Organik Tarım",
  "Tıbbi ve Aromatik Bitkiler",
  "Yenilenebilir Enerji Kaynakları",
  "Ağaç İşleri Endüstri Mühendisliği",
  "Seracılık",
  "Tohum Teknolojisi",
  "Bitki Koruma",
  "Yapı Denetimi",
  "Yapı Ressamlığı",
  "Doğalgaz ve Tesisatı Teknolojisi",
  "Kaynak Teknolojisi",
  "Kalıpçılık",
  "CNC Operatörlüğü",
  "Matbaacılık ve Baskı Teknolojileri",
  "Kuyumculuk ve Mücevher Tasarımı",
  "Halıcılık ve El Sanatları",
  "Mücevher Tasarımı",
  "El Sanatları",
  "Çevre Koruma ve Kontrol",
  "Çevre Sağlığı",
  "İş Sağlığı ve Güvenliği",
  "Adli Bilişim Mühendisliği",
  "Adli Bilimler",
  "Kriminoloji",
  "Uluslararası Hukuk",
  "Medya Hukuku",
  "Dijital Pazarlama",
  "Sosyal Medya Yönetimi",
  "Finans ve Bankacılık",
  "Risk Yönetimi",
  "Tedarik Zinciri Yönetimi",
  "Proje Yönetimi",
  "Kurumsal İletişim",
  "Stratejik İletişim",
  "Marka İletişimi",
  "Spor Gazeteciliği",
  "Savaş Muhabirliği",
  "Belgesel Filmcilik",
  "Animasyon",
  "Karikatür",
  "İllüstrasyon",
  "Seramik ve Cam Tasarımı",
  "Metal ve Takı Tasarımı",
  "Moda ve Tekstil",
  "Uluslararası Lojistik ve Taşımacılık",
  "Uluslararası Finans ve Bankacılık",
  "Havalimanı İşletme",
  "Sivil Havacılık İşletmeciliği",
  "Kokpit (Pilotaj)",
  "Kabin Memurluğu",
  "Sağlık Kurumları İşletmeciliği",
  "Sağlık Bilişimi",
  "Tıp Mühendisliği",
  "Çevre Tasarımı",
  "Kent ve Çevre Planlaması",
  "Bilim Tarihi",
  "Eğitim Teknolojisi",
  "Uzaktan Algılama ve Coğrafi Bilgi Sistemleri",
  "Bilgisayar Grafiği ve Oyun Teknolojileri",
  "Robotik",
  "Endüstriyel Otomasyon",
  "Biyofizik",
  "Biyokimya",
  "Tıbbi Biyoloji",
  "Tıbbi Mikrobiyoloji",
  "İmmünoloji",
  "Farmakoloji",
  "Fizyoloji",
  "Anatomi",
  "Histoloji ve Embriyoloji",
  "Hücre ve Moleküler Biyoloji",
  "Deniz Biyolojisi",
  "Çevre Biyolojisi",
  "Ekoloji",
  "Hidrobiyoloji",
  "Toprak Mühendisliği",
  "Gıda Bilimi ve Teknolojisi",
  "Bahçe ve Tarla Bitkileri",
  "Biyosistem Mühendisliği",
  "Kentsel Dönüşüm",
  "Afet Yönetimi",
  "Sivil Savunma ve İtfaiyecilik",
  "Acil Durum ve Afet Yönetimi",
  "Sosyal Politika",
  "Siyaset ve Ekonomi",
  "Küresel Siyaset ve Uluslararası İlişkiler",
  "Diplomasi ve Uluslararası İlişkiler",
  "Avrupa Birliği İlişkileri",
  "Karşılaştırmalı Siyaset",
  "Uluslararası Güvenlik ve Terörizm",
];
