
ALTER TABLE public.deneme_results
  ADD COLUMN IF NOT EXISTS student_area text DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS ayt_matematik_dogru integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS ayt_matematik_yanlis integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS ayt_matematik_net numeric NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS ayt_fizik_dogru integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS ayt_fizik_yanlis integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS ayt_fizik_net numeric NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS ayt_kimya_dogru integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS ayt_kimya_yanlis integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS ayt_kimya_net numeric NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS ayt_biyoloji_dogru integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS ayt_biyoloji_yanlis integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS ayt_biyoloji_net numeric NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS ayt_edebiyat_dogru integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS ayt_edebiyat_yanlis integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS ayt_edebiyat_net numeric NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS ayt_tarih1_dogru integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS ayt_tarih1_yanlis integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS ayt_tarih1_net numeric NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS ayt_cografya1_dogru integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS ayt_cografya1_yanlis integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS ayt_cografya1_net numeric NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS ayt_tarih2_dogru integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS ayt_tarih2_yanlis integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS ayt_tarih2_net numeric NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS ayt_cografya2_dogru integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS ayt_cografya2_yanlis integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS ayt_cografya2_net numeric NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS ayt_felsefe_dogru integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS ayt_felsefe_yanlis integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS ayt_felsefe_net numeric NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS ayt_din_dogru integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS ayt_din_yanlis integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS ayt_din_net numeric NOT NULL DEFAULT 0;
